console.log(`styles.js loaded`)

const styles = [
  {
    id: "clr",
    name: "Colours",
    key: "clr",
    keys: [
      {
        id: "text",
        key: "color",
      },
      {
        id: "bg",
        key: "background-color",
      },
      {
        id: "fill",
        key: "fill",
      },
    ],
    min: 0,
    max: 0,
    value: "",
    values: [
      {
        id: "pri",
        name: "Primary",
        key: "primary",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "sec",
        name: "Secondary",
        key: "secondary",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "acc-1",
        name: "Accent 1",
        key: "accent-1",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "gray",
        name: "Grays",
        key: "gray",
        keys: [],
        min: 0,
        max: 1000,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
    ],
  },
  {
    id: "ff",
    name: "Font Families",
    key: "font-family",
    keys: [],
    min: 0,
    max: 0,
    value: "",
    values: [
      {
        id: "primary",
        name: "Primary",
        key: "primary",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "secondary",
        name: "Secondary",
        key: "secondary",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "monospace",
        name: "Monospace",
        key: "monospace",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "fz",
    name: "Font Sizes",
    key: "font-size",
    keys: [],
    min: 0,
    max: 900,
    value: "",
    values: [
      {
        id: "0",
        name: "0",
        key: "0",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "50",
        name: "50",
        key: "50",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "fw",
    name: "Font Weights",
    key: "font-weight",
    keys: [],
    min: 0,
    max: 0,
    value: "",
    values: [
      {
        id: "thin",
        name: "Thin",
        key: "thin",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "extra-light",
        name: "Extra Light",
        key: "extra-light",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "light",
        name: "Light",
        key: "light",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "regular",
        name: "Regular",
        key: "regular",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "medium",
        name: "Medium",
        key: "medium",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "semi-bold",
        name: "Semi-bold",
        key: "semi-bold",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "bold",
        name: "Bold",
        key: "bold",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "extra-bold",
        name: "Extra Bold",
        key: "extra-bold",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "black",
        name: "Black",
        key: "black",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "f",
    name: "Fixed Sizes",
    key: "size",
    keys: [
      {
        id: "m",
        name: "Margins",
        key: "margin",
      },
      {
        id: "m-n",
        name: "Negative Margins",
        key: "margin",
      },
      {
        id: "p",
        name: "Paddings",
        key: "padding",
      },
    ],
    min: 0,
    max: 1000,
    value: "",
    values: [
      {
        id: "auto",
        name: "Auto",
        key: "auto",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "0",
        name: "0",
        key: "0",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "50",
        name: "50",
        key: "50",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
]
