console.log(`styles.js loaded`)

const styles = [
  {
    id: "clr",
    name: "Colours",
    key: "clr",
    keys: [
      {
        id: "text",
        key: "color",
      },
      {
        id: "bg",
        key: "background-color",
      },
      {
        id: "fill",
        key: "fill",
      },
    ],
    min: 0,
    max: 0,
    useVar: true,
    value: "",
    values: [
      {
        id: "pri",
        name: "Primary",
        key: "primary",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "sec",
        name: "Secondary",
        key: "secondary",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "acc-1",
        name: "Accent 1",
        key: "accent-1",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "gray",
        name: "Grays",
        key: "gray",
        keys: [],
        min: 0,
        max: 1000,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
    ],
  },
  {
    id: "ff",
    name: "Font Families",
    key: "font-family",
    keys: [],
    min: 0,
    max: 0,
    useVar: true,
    value: "",
    values: [
      {
        id: "primary",
        name: "Primary",
        key: "primary",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "secondary",
        name: "Secondary",
        key: "secondary",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "monospace",
        name: "Monospace",
        key: "monospace",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "fz",
    name: "Font Sizes",
    key: "font-size",
    keys: [],
    min: 0,
    max: 900,
    useVar: true,
    value: "",
    values: [
      {
        id: "0",
        name: "0",
        key: "0",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "50",
        name: "50",
        key: "50",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "fw",
    name: "Font Weights",
    key: "font-weight",
    keys: [],
    min: 0,
    max: 0,
    useVar: true,
    value: "",
    values: [
      {
        id: "thin",
        name: "Thin",
        key: "thin",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "extra-light",
        name: "Extra Light",
        key: "extra-light",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "light",
        name: "Light",
        key: "light",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "regular",
        name: "Regular",
        key: "regular",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "medium",
        name: "Medium",
        key: "medium",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "semi-bold",
        name: "Semi-bold",
        key: "semi-bold",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "bold",
        name: "Bold",
        key: "bold",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "extra-bold",
        name: "Extra Bold",
        key: "extra-bold",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "black",
        name: "Black",
        key: "black",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "f",
    name: "Fixed Sizes",
    key: "size",
    keys: [
      {
        id: "m",
        name: "Margins",
        key: "margin",
      },
      {
        id: "m-n",
        name: "Negative Margins",
        key: "margin",
      },
      {
        id: "p",
        name: "Paddings",
        key: "padding",
      },
    ],
    min: 0,
    max: 1000,
    useVar: true,
    value: "",
    values: [
      {
        id: "auto",
        name: "Auto",
        key: "auto",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "0",
        name: "0",
        key: "0",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "50",
        name: "50",
        key: "50",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "v",
    name: "Variable Sizes",
    key: "size",
    keys: [
      {
        id: "m",
        name: "Margins",
        key: "margin",
      },
      {
        id: "m-n",
        name: "Negative Margins",
        key: "margin",
      },
      {
        id: "p",
        name: "Paddings",
        key: "padding",
      },
    ],
    min: 0,
    max: 1000,
    useVar: true,
    value: "",
    values: [
      {
        id: "auto",
        name: "Auto",
        key: "auto",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "0",
        name: "0",
        key: "0",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "50",
        name: "50",
        key: "50",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "ta",
    name: "Text Aligns",
    key: "text-align",
    keys: [],
    min: 0,
    max: 0,
    useVar: false,
    value: "",
    values: [
      {
        id: "left",
        name: "Left",
        key: "left",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "center",
        name: "Center",
        key: "center",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "right",
        name: "Right",
        key: "right",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "d",
    name: "Displays",
    key: "display",
    keys: [],
    min: 0,
    max: 0,
    useVar: false,
    value: "",
    values: [
      {
        id: "block",
        name: "Block",
        key: "block",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "inline",
        name: "Inline",
        key: "inline",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "inline-block",
        name: "Inline Block",
        key: "inline-block",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "flex",
        name: "Flex",
        key: "flex",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "inline-flex",
        name: "Inline Flex",
        key: "inline-flex",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "grid",
        name: "Grid",
        key: "grid",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "inline-grid",
        name: "Inline Grid",
        key: "inline-grid",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "fd",
    name: "Flex Directions",
    key: "flex-directions",
    keys: [],
    min: 0,
    max: 0,
    useVar: false,
    value: "",
    values: [
      {
        id: "row",
        name: "Row",
        key: "row",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "row-reverse",
        name: "Row Reverse",
        key: "row-reverse",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "column",
        name: "Column",
        key: "column",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "column-reverse",
        name: "Column Reverse",
        key: "column-reverse",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "ai",
    name: "Align Items",
    key: "align-items",
    keys: [],
    min: 0,
    max: 0,
    useVar: false,
    value: "",
    values: [
      {
        id: "center",
        name: "Center",
        key: "center",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "start",
        name: "Start",
        key: "start",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "end",
        name: "End",
        key: "end",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "flex-start",
        name: "Flex Start",
        key: "flex-start",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "flex-end",
        name: "Flex End",
        key: "flex-end",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "self-start",
        name: "Self Start",
        key: "self-start",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "self-end",
        name: "Self End",
        key: "self-end",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "jc",
    name: "Justify Content",
    key: "justify-content",
    keys: [],
    min: 0,
    max: 0,
    value: "",
    values: [
      {
        id: "center",
        name: "Center",
        key: "center",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "start",
        name: "Start",
        key: "start",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "end",
        name: "End",
        key: "end",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "flex-start",
        name: "Flex Start",
        key: "flex-start",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "flex-end",
        name: "Flex End",
        key: "flex-end",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "left",
        name: "Left",
        key: "left",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "right",
        name: "Right",
        key: "right",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "normal",
        name: "Normal",
        key: "normal",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "space-between",
        name: "Space Between",
        key: "space-between",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "space-around",
        name: "Space Around",
        key: "space-around",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "space-evenly",
        name: "Space Evenly",
        key: "space-evenly",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "stretch",
        name: "Stretch",
        key: "stretch",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "ji",
    name: "Justify Items",
    key: "justify-items",
    keys: [],
    min: 0,
    max: 0,
    useVar: false,
    value: "",
    values: [
      {
        id: "normal",
        name: "Normal",
        key: "normal",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "stetch",
        name: "Stretch",
        key: "stetch",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "center",
        name: "Center",
        key: "center",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "start",
        name: "Start",
        key: "start",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "end",
        name: "End",
        key: "end",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "flex-start",
        name: "Flex Start",
        key: "flex-start",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "flex-end",
        name: "Flex End",
        key: "flex-end",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "self-start",
        name: "Self Start",
        key: "self-start",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "self-end",
        name: "Self End",
        key: "self-end",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "left",
        name: "Left",
        key: "left",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "right",
        name: "Right",
        key: "right",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "td",
    name: "Text Decoration",
    key: "text-decoration",
    keys: [],
    min: 0,
    max: 0,
    useVar: false,
    value: "",
    values: [
      {
        id: "none",
        name: "None",
        key: "none",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "underline",
        name: "Underline",
        key: "underline",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "overline",
        name: "Overline",
        key: "overline",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
]
