console.log(`styles.js loaded`)

const styles = [
  {
    id: "clr",
    name: "Colours",
    key: "",
    keys: [
      {
        id: "text",
        key: "color",
      },
      {
        id: "bg",
        key: "background-color",
      },
      {
        id: "fill",
        key: "fill",
      },
    ],
    min: 0,
    max: 0,
    value: "",
    values: [
      {
        id: "pri",
        name: "Primary",
        key: "primary",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "sec",
        name: "Secondary",
        key: "secondary",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "acc-1",
        name: "Accent 1",
        key: "accent-1",
        keys: [],
        min: 0,
        max: 900,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
      {
        id: "gray",
        name: "Grays",
        key: "gray",
        keys: [],
        min: 0,
        max: 1000,
        value: "",
        values: [
          {
            id: "50",
            name: "50",
            key: "50",
            keys: [],
            min: 0,
            max: 0,
            value: "",
            values: [],
          },
        ],
      },
    ],
  },
  {
    id: "ff",
    name: "Font Families",
    key: "font-family",
    keys: [],
    min: 0,
    max: 0,
    value: "",
    values: [
      {
        id: "primary",
        name: "Primary",
        key: "primary",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "secondary",
        name: "Secondary",
        key: "secondary",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "monospace",
        name: "Monospace",
        key: "monospace",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
  {
    id: "fz",
    name: "Font Sizes",
    key: "font-size",
    keys: [],
    min: 0,
    max: 900,
    value: "",
    values: [
      {
        id: "0",
        name: "0",
        key: "0",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
      {
        id: "50",
        name: "50",
        key: "50",
        keys: [],
        min: 0,
        max: 0,
        value: "",
        values: [],
      },
    ],
  },
]
